export const LOCALTRAIN_EVENTS = {
  BEHAVIOUR_EXECUTION_START: 'BEHAVIOUR_EXECUTION_START',
  BEHAVIOUR_EXECUTION_COMPLETE: 'BEHAVIOUR_EXECUTION_COMPLETE',
  AGENT_EXECUTION_COMPLETE: 'AGENT_EXECUTION_COMPLETE',
  AGENT_EXECUTION_START: 'AGENT_EXECUTION_START',
  LLM_STREAM: 'LLM_STREAM',
  EXECUTION_INTERRUPTED: "EXECUTION_INTERRUPTED"
}
